language: ruby
rvm:
- 2.2
script:
- bundle exec jekyll build
after_success:
- git clone https://$GITHUB_REPO
- cd ${GITHUB_REPO_NAME}
- git config user.name "Travis CI"
- git config user.email ${EMAIL}
- rsync -az --delete --exclude '.git*' ../_site/ .
- touch .nojekyll
- git add -A .
- git commit -m "Commit ${TRAVIS_COMMIT} - Generated Jekyll site by Travis CI - Build ${TRAVIS_BUILD_NUMBER}"
- git push --force "https://${DEPLOY_KEY}@${GITHUB_REPO}" HEAD:${REPO_TARGET_BRANCH}
branches:
  only: develop
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GITHUB_REPO: github.com/${TRAVIS_REPO_SLUG}.git
  - GITHUB_REPO_NAME: staph-disease
  - REPO_TARGET_BRANCH: gh-pages
  - secure: DwWTptke8I3sVBrKYzXs/6GIZEVPnKfdoW2JdnxuH01j0JMmBOwu14uxOEk1MsiboJIXduJeih5Ysgyi1Ki0fGqWySSi3GXyWvBUTtXVx16t+ZxpAAMo+DSWH8TPvJJWroYmSsxxWkBXRTmjvdgxtGAy1C2RTzZZaZXtArkou+YY6dUw9OTnJZI4SS/lsPDwTjUsSGNI0fVdP97TYYtyKCCvypxJYkRJRne08efa1eiUecFL7fDJ3QdSvKHTPG4wVhknN/hNmB7344YDQWLqcqcbJbGAFdA5zVtzvzCOt9MY+MjDEpWAH3pTjJky1iHvQDnc2gpNKyZxKngvfqal626t2TGvSm6E1q5e2oMrMWK1XXlEuvAwO5AyAhm+JN4iTMK8QItV5RjYUWItlG4QCMVEOvS+FBJOmdULYI3wGdEK9CXdP6pEKrRYU2/rhozyVyKo70wLQW4mmPdaxvVqQqO2MHXCwhoiDHFDAl74f/OHm6AIjqRnJfZqSYzglGBIqSe8quPVIZMRIE8VxIh2wVPIx1cN2mqi+bQoOpqpCiKG+b6LO9WmF/I3XnO1SL8xNDj9qCZgz4pBif6tx7UXKepve8er09OHo1F49btsfSAZhXmmSr0zkNI8h5OVQuIXpeHd5EqgwphD2DMpUVSstzSo494pJ4NzFc3aikVPr7k=
  - secure: UodUyUMCLg+/zFGtg7CxnrYHUjsYQ22ahQ/nL+xLRA5qQtraffke6xbh3Lbrl0JIVNqXLEW2vxhgg6NGQOQUBkLrt6UyokJrxpw+0vRBEK9MaVUg/gXNIsZls3bS32y5FEoq8bdU6ss9lMjYN38ZuSG4vgZ6uVzhaYGoIm+8kBGv6hQvQL/wpVWmhXIK4WUegwqQ53mfv7w085qYf5gCnt2FQYjSKBwmo/dtGqzNYDqwRbHI+pHL3wCRrOHZh3yKOC1UK1aV84C7rkP4dirQEZTlAC0uX0TnM9FSPR0oiskoa9gswuH2AimchnRZGTfqV/S8r2eMVet5i71okNCduWZGwe8AvGfNy/yWKop+GB00lrCP2tgb6U8yNWIaXKNwPRzI/zwIZ9755or8vHt1NzF/sIWe8kZDuhdVWDxNGuqsvViiDse3jL5UNYZZy9mJg7vGFvY4+btSsHhiTYvMYdef19KikhIjWHE/Tf5UXBJkxOQEZdiTzQlLQSI2LCeE5E51rvq7jzkBJkmgcmQgyDPDK5bJ618uk1NPsuaOu7N1Ui2jM6rohqWax889xwTCJbMyvXdsXrbnur0A/DJ+Zs3kL86FwNy4Ppj3WTC79o9GqRGrQXACMJ36vNIzzoPOU6bwpXPylj5AW41/AaV7m/KKcwH25lt5z3Jw7aRAlOA=
