language: ruby
rvm:
- 2.2
script:
- bundle exec jekyll build
after_success:
- git clone https://$GITHUB_REPO
- cd ${GITHUB_REPO_NAME}
- git config user.name "Travis CI"
- git config user.email ${EMAIL}
- rsync -az --delete --exclude '.git*' ../_site/ .
- touch .nojekyll
- git add -A .
- git commit -m "Commit ${TRAVIS_COMMIT} - Generated Jekyll site by Travis CI - Build
  ${TRAVIS_BUILD_NUMBER}"
- git push --force "https://${DEPLOY_KEY}@${GITHUB_REPO}" HEAD:${REPO_TARGET_BRANCH} --quiet
branches:
  only: develop
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GITHUB_REPO: github.com/${TRAVIS_REPO_SLUG}.git
  - GITHUB_REPO_NAME: staph-disease
  - REPO_TARGET_BRANCH: gh-pages
  - secure: QCIN1K5R1aOZih05n2HNJCHHAxw/IeHJruz1YqLCwM+KAAq/mTSWXV/sR0t1xhYyNawNy6kDByT97dLNGcWQBZxaDjvXzPvBHyIuTqCqcDvhSdvfQroA6y4a4rdckbg1bN/YMKSJBaeeEP7x8GFF5dePJ0TmkPjN3mLv4qCw49x4gwzQj7kYZnDRsMaSYnDD/Ec1j23VKFcjm/HxEqwnZZW8i687RPczIhWC/stvp/k8j/5PUPpGG4BHV5/pe/qzzQqEmDaw7cAGOd/BFQFKWOWKmRdGslma7IHZ9q2LJpew/inSyLR9Owf+2+lCznskwk9I5Uj0bdGFDJx3XTFWDRwLd5QJCqgyEZEykjJovm7c9zeulKB9dg+QbTMPBr9udE8M7kLHQAOsfnJb7u2LNfPJWsch2zPheOWKjcWof6QYQirE0OL28seUAiouNCXsb4hjQ3XL0ttQuWCXwaKGxpYPpkUCMNZYDCYel7euyxFTxMuEPDPv4EjkgozoSzJdCCWLibhsxAYpZlsGK6sU8rBy0SXUK0CafNin4XhGypuyhhjRiHTIgKkfs9Ljar4zCmPEyyac10JlMD/KzZvX7oN2mzRUl7XQK4GO++JwLDUBqIkYEYtlLBBEGiEKV5ZM72DcUM7o5M4S6dImjoBf15aTBfetu/UiIyz4qFYCKsY=
  - secure: l6ffyZpWEnYR3nbpQisyuWXOzLJ/IGJxfvqLg6XgCy3wOCRVi5J3xHU8SDuJ8axXeqIirJgVtJ37K4JNyEvLGQxE7W8ngDkCODp1z1eVGTD+GnAgmcc0GoiWFubyBsJekjYFd8SgBUl07lki8p7JGfTfitmKyTMXogjZ02rdkPynhbGnIljNxiH8r6Lb8+Gy4ug1T6C5L4ZG4S2n2hHqcRHkE/JoADLgERM6p+cVRQr7f1ZTL8646rYBBoCUeMxrsL9LBcOg5z1sPpDC0o41XBFb9/NlUbqM8X1iDLz9YNGEboEhU0nYkKKFgrIVbm8XlEkiCp98Pq9fdRgsUh7QhAhxRjZBoZdO74s2GR1V20zdcKGQdYnbs9zV98OuY/kzCalbl/T1MmbM9G/DQjjA77VjUhsyS8usfiwcPF6P3JujFQpdq0JSBtzgd2raKgw7qeBPWDvGZeacvd0c+cXPtTzi6YzWfALOUo8dFN7BhOv/zsZuKHimNFHQLQSZSxrhQV38VgjpFwnTiQmw4MNrLfOUQ+io+hzNnSn0tSFow9XO67ICVpCX8jdhpYV1FYg6HILLZ0lDgtaTCwqporRft7FSH4uF0Yt4oOosDS5gOBtc0+GwI2W+5y8HUy53Q7Mu4jajptWJJY62LUo5hlQm0IFpI2TUdYKZ7/GZNf8Q8Iw=
