# Site settings
home_slug: staph-disease
title: Staph Infection
tag_text: Staph Infection
description: Solo is a Jekyll theme that supports single-page websites only, but supports them well. Yes, it’s responsive.

# Build settings
markdown: kramdown
exclude: ["Gemfile", "Gemfile.lock", "vendor"]
sass:
  style: compressed
