# Site settings
home_slug: staph-disease
title: Staph Infection
tag_text: Staph Infection
description: Staphylococcus Aureus - Pathogens and Human Disease Project for Honors Biology - Ryan Blue

# Build settings
markdown: kramdown
exclude: ["README.md", "Gemfile", "Gemfile.lock", "vendor"]
sass:
  style: compressed
